#ifndef __SERVICE_TYPES_HPP__
#define __SERVICE_TYPES_HPP__
#include <iostream>
#include <string>
using namespace std;
#define MAX_WAITING_CUSTOMER 10
typedef enum barberShopServiceType
{
	SHAVING,
	HAIR_CUT,
	HAIR_COLOR,
	FACE_WASH,
	BLEACH,
	FACIAL,
	SHAING_AND_HAIR_CUT,
	SHAVING_HAIR_CUT_AND_HAIR_COLOR,
	SHAVING_AND_FACE_WASH,
	SHAVING_AND_BLEACH,
	SHAVING_AND_FACIAL,
	MAX_SERVICE
}barberShopServiceType_t;

string serviceNameArray[12]={"SHAVING","HAIR_CUT","HAIR_COLOR","FACE_WASH",
	"BLEACH","FACIAL","SHAING_AND_HAIR_CUT","SHAVING_HAIR_CUT_AND_HAIR_COLOR",
	"SHAVING_AND_FACE_WASH","SHAVING_AND_BLEACH","SHAVING_AND_FACIAL"};
int serviceDurationVal[12]={5,10,12,11,16,15,15,27,28,21,30};

barberShopServiceType_t valArray[32] = {
	SHAVING,
	HAIR_CUT,
	HAIR_CUT,
	SHAVING,
	HAIR_COLOR,
	SHAVING,
	SHAVING,
	HAIR_CUT,
	HAIR_CUT,
	HAIR_COLOR,
	HAIR_COLOR,
	FACE_WASH,
	BLEACH,
	HAIR_CUT,
	FACIAL,
	SHAVING,
	SHAING_AND_HAIR_CUT,
	FACIAL,
	SHAVING,
	SHAVING,
	SHAVING_HAIR_CUT_AND_HAIR_COLOR,
	SHAING_AND_HAIR_CUT,
	HAIR_CUT,
	HAIR_CUT,
	SHAVING_AND_FACE_WASH,
	SHAVING_AND_BLEACH,
	SHAING_AND_HAIR_CUT,
	SHAVING,
	SHAVING_AND_FACIAL,
	SHAING_AND_HAIR_CUT,
	FACE_WASH,
	SHAVING_HAIR_CUT_AND_HAIR_COLOR
};
#endif